trigger:
  branches:
    include:
      - feature/ci-cd
      - develop
      - main  

pool:
  vmImage: ubuntu-latest
#########################################
#------Stage 1 - Application Tests------#
#########################################
stages:
  - stage: Test
    displayName: Stage 1 - Application Tests

    jobs:
      - job: BackendTests
        displayName: Backend Tests

        steps:
          - checkout: self

          - task: UsePythonVersion@0
            displayName: Setup Python
            inputs:
              versionSpec: '3.12'

          - script: |
              python -m pip install --upgrade pip
              pip install -r src/note_backend/requirements.txt
              pip install pytest
            displayName: Install Backend Dependencies

          - script: |
              export PYTHONPATH="$(Build.SourcesDirectory):$PYTHONPATH"

              pytest tests/ \
                --junitxml=$(Common.TestResultsDirectory)/pytest-results.xml
            displayName: Run Backend Tests

          - task: PublishTestResults@2
            displayName: Publish Backend Test Results
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: JUnit
              testResultsFiles: '$(Common.TestResultsDirectory)/pytest-results.xml'
              testRunTitle: Backend Pytest Results

      - job: FrontendBuildCheck
        displayName: Frontend Build Check

        steps:
          - checkout: self

          - task: UseNode@1
            displayName: Setup Node.js
            inputs:
              version: '24.x'

          - script: |
              npm ci --legacy-peer-deps
              npm run build
            workingDirectory: src/note_frontend
            displayName: Build Frontend
#########################################
#------Stage 2 - Security Scan----------#
#########################################
  - stage: Security
    displayName: Stage 2 - Trivy Security Scan
    dependsOn: Test
    condition: succeeded()

    jobs:
      - job: TrivyScan
        displayName: Trivy Security Scan

        steps:
          - checkout: self

          - script: |
              curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
                | sudo sh -s -- -b /usr/local/bin v0.74.0

              trivy --version
            displayName: Install Trivy

          - script: |
              trivy fs \
                --scanners vuln \
                --severity HIGH,CRITICAL \
                --ignorefile .trivyignore.yaml \
                --exit-code 1 \
                .
            displayName: Vulnerability Security Gate

          - script: |
              trivy fs \
                --scanners secret \
                --exit-code 1 \
                .
            displayName: Secret Security Gate

          - script: |
              trivy fs \
                --scanners misconfig \
                --severity HIGH,CRITICAL \
                --exit-code 0 \
                .
            displayName: IaC Misconfiguration Scan
#########################################
#------Stage 3 - Docker Build-----------#
#########################################
  - stage: Build
    displayName: Stage 3 - Docker Build
    dependsOn: Security
    condition: succeeded()

    jobs:

      # Backend Image
      - job: BackendBuild
        displayName: Build Backend Image

        steps:
          - checkout: self

          - script: |
              docker build \
                -t note-backend:$(Build.BuildId) \
                src/note_backend
            displayName: Build Backend Docker Image

          - script: |
              mkdir -p $(Build.ArtifactStagingDirectory)/backend

              docker save \
                note-backend:$(Build.BuildId) \
                -o $(Build.ArtifactStagingDirectory)/backend/backend-image.tar
            displayName: Export Backend Docker Image

          - task: PublishPipelineArtifact@1
            displayName: Publish Backend Image Artifact
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/backend'
              artifact: 'backend-image'
              publishLocation: 'pipeline'


      # Frontend Image
      - job: FrontendBuild
        displayName: Build Frontend Image

        steps:
          - checkout: self

          - script: |
              docker build \
                -t note-frontend:$(Build.BuildId) \
                src/note_frontend
            displayName: Build Frontend Docker Image

          - script: |
              mkdir -p $(Build.ArtifactStagingDirectory)/frontend

              docker save \
                note-frontend:$(Build.BuildId) \
                -o $(Build.ArtifactStagingDirectory)/frontend/frontend-image.tar
            displayName: Export Frontend Docker Image

          - task: PublishPipelineArtifact@1
            displayName: Publish Frontend Image Artifact
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/frontend'
              artifact: 'frontend-image'
              publishLocation: 'pipeline'

