apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: {{ .Release.Namespace }}
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS messages (
        id SERIAL PRIMARY KEY,
        text TEXT
    );