apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ required "postgres.auth.password is required" .Values.postgres.auth.password | quote }}