apiVersion: v1
kind: ConfigMap

metadata:
  name: postgres-init
  namespace: note-app

data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS messages (
        id SERIAL PRIMARY KEY,
        text TEXT
    );